language: cpp
sudo: false
compiler:
  - gcc

env:
  global:
    - GCC_VERSION="4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-4.8
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev
    - libxcb
    - libxcb1-dev

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
- git clone https://github.com/SFML/SFML && cd SFML && mkdir build && cd build
- cmake .. && make && make install


script:
- cmake .
- make
- make install
