language: cpp
sudo: false
compiler:
  - gcc

env:
  global:
    - GCC_VERSION="5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-5
    - gcc-5
    - cmake
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev
    - libxbc-image0-dev
    - libx11-xcb-dev
    - libxcb-icccm4-dev
    - libxcb-image0
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb1-dev

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
- wget --no-check-certificate  https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz
- tar -zxf cmake-3.4.0.tar.gz && cd cmake-3.4.0 && ./bootstrap --prefix=$(pwd)
- make && make install && export cmake3=$(pwd)/bin/cmake && cd ..
- pwd
- git clone https://github.com/SFML/SFML && cd SFML && git checkout 2.2
- export SFML_ROOT=$(pwd)
- mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install .. && make && make install
- pwd


script:
- cd ../.. && mkdir build && cd build
- pwd
- cmake -DSFML_ROOT=$SFML_ROOT -DSLOW_SEARCH=TRUE -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
- make
- make install
