language: cpp
dist: xenial
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-9
    - gcc-9
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libvorbis-dev
    - libflac-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev
    - libx11-xcb-dev
    - libxcb-icccm4-dev
    - libxcb-image0
    - libxcb-image0-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb1-dev

jobs:
  - name: "linux gcc dynamic"
    language: cpp
    os: linux
    dist: xenial
    compiler:
      - gcc
    services:
      - xvfb
    env:
      - GCC_VERSION="9"
    install:
      - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
      - git clone https://github.com/SFML/SFML && cd SFML
      - export SFML_ROOT=$(pwd)/build/install
      - mkdir build && cd build
      - cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install .. && make install && cd ../..

    script:
      - mkdir build && cd build
      - cmake -DSFML_ROOT=$SFML_ROOT -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
      - make install
    
  - name: "Android armeabi-v7a"
    language: android
    os: linux
    dist: trusty
    android:
      components:
        - tools
        - android-26
        - platform-tools
        - build-tools-26.0.2
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    env:
      - ANDROID_SDK=/usr/local/android-sdk
      - ANDROID_NDK=$TRAVIS_BUILD_DIR/android-ndk-r18b
      - ANDROID_FLAGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=$ANDROID_NDK -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang -DCMAKE_ANDROID_STL_TYPE=c++_shared -DCMAKE_ANDROID_API=26"

    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

    install:
      - echo y | sdkmanager "cmake;3.10.2.4988404"
      - sudo ln -sf /usr/local/android-sdk/cmake/3.10.2.4988404/bin/cmake /usr/bin/cmake
      - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
      - unzip -qq android-ndk-r18b-linux-x86_64.zip
      - git clone https://github.com/SFML/SFML && cd SFML && mkdir build && cd build
      - export SFML_ANDROID_ROOT=${ANDROID_NDK}/sources/third_party/SFML
      - cmake $ANDROID_FLAGS -DCMAKE_INSTALL_PREFIX=${SFML_ANDROID_ROOT} .. && make install && cd ../..
      - cd android && echo "sdk.dir=${ANDROID_SDK}/" > local.properties && echo "ndk.dir=${ANDROID_NDK}/" >> local.properties

    script:
      - ./gradlew build
